### ISSUE TITLE
Milestones to 1.0 Release

### ISSUE THREAD

**Issue by neeboo** [harmony-one/sdk#5]
# Features
- [ ] Add missing RPC API to `Blockchain` class
- [ ] Fix broken types as much as possible(typescript)

# Documentation:
- [ ] Use `TypeDoc` to generate all function/feature api.
- [ ] Remake build script
- [ ] Make every intro `README.md` to each package
- [ ] Write guide for each package
- [ ] An api site can be accessed via gh-page

# Tests
- [ ] Increase test coverage to 75% in general
- [ ] More unit test
- [ ] Remake integration test (TestNet)
- [ ] Remake e2e test (Local Testnet)
